# Sensor
sensor:
  baseUrl: http://192.168.136.110/iolinkmaster/port[0]/iolinkdevice/pdin/getdata
  timeout: 1 # in seconds

# MongoDB
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: barrels-of-beer

# Logging
sentry:
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: debug
  dsn: <hidden>
  traces-sample-rate: 1.0