# Sensor
sensor:
  baseUrl: http://192.168.136.110/iolinkmaster/port[SENSOR_ID]/iolinkdevice/pdin/getdata
  timeout: 5 # in seconds

# Spring, MongoDB
spring:
  banner:
    location: banner.txt
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: barrels-of-beer

# Logging
sentry:
  logging:
    minimum-event-level: info
    minimum-breadcrumb-level: debug
  dsn: <hidden>
  traces-sample-rate: 1.0